export const TIMEZONE_OPTIONS = [
  { value: "", label: "Not listed" },
  { value: "America/New_York", label: "Eastern Time — America/New_York" },
  { value: "America/Chicago", label: "Central Time — America/Chicago" },
  { value: "America/Denver", label: "Mountain Time — America/Denver" },
  { value: "America/Los_Angeles", label: "Pacific Time — America/Los_Angeles" },
  { value: "America/Anchorage", label: "Alaska Time — America/Anchorage" },
  { value: "Pacific/Honolulu", label: "Hawaii Time — Pacific/Honolulu" },
  { value: "America/Toronto", label: "Toronto — America/Toronto" },
  { value: "America/Vancouver", label: "Vancouver — America/Vancouver" },
  { value: "America/Mexico_City", label: "Mexico City — America/Mexico_City" },
  { value: "America/Sao_Paulo", label: "São Paulo — America/Sao_Paulo" },
  { value: "Europe/London", label: "London — Europe/London" },
  { value: "Europe/Paris", label: "Paris — Europe/Paris" },
  { value: "Europe/Berlin", label: "Berlin — Europe/Berlin" },
  { value: "Europe/Madrid", label: "Madrid — Europe/Madrid" },
  { value: "Europe/Rome", label: "Rome — Europe/Rome" },
  { value: "Asia/Dubai", label: "Dubai — Asia/Dubai" },
  { value: "Asia/Kolkata", label: "India — Asia/Kolkata" },
  { value: "Asia/Bangkok", label: "Bangkok — Asia/Bangkok" },
  { value: "Asia/Singapore", label: "Singapore — Asia/Singapore" },
  { value: "Asia/Tokyo", label: "Tokyo — Asia/Tokyo" },
  { value: "Asia/Seoul", label: "Seoul — Asia/Seoul" },
  { value: "Australia/Sydney", label: "Sydney — Australia/Sydney" },
  { value: "Pacific/Auckland", label: "Auckland — Pacific/Auckland" },
];

export const REGION_OPTIONS = [
  { value: "", label: "Not listed" },
  { value: "US", label: "United States" },
  { value: "CA", label: "Canada" },
  { value: "MX", label: "Mexico" },
  { value: "BR", label: "Brazil" },
  { value: "GB", label: "United Kingdom" },
  { value: "IE", label: "Ireland" },
  { value: "FR", label: "France" },
  { value: "DE", label: "Germany" },
  { value: "ES", label: "Spain" },
  { value: "IT", label: "Italy" },
  { value: "NL", label: "Netherlands" },
  { value: "SE", label: "Sweden" },
  { value: "NO", label: "Norway" },
  { value: "DK", label: "Denmark" },
  { value: "PL", label: "Poland" },
  { value: "UA", label: "Ukraine" },
  { value: "IN", label: "India" },
  { value: "JP", label: "Japan" },
  { value: "KR", label: "South Korea" },
  { value: "CN", label: "China" },
  { value: "SG", label: "Singapore" },
  { value: "AU", label: "Australia" },
  { value: "NZ", label: "New Zealand" },
  { value: "ZA", label: "South Africa" },
];